# -*- coding: utf-8 -*-
"""Seasonal Agriculture Performance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEKv2NqgAT7nOImdVP1dk6p9AJTE_lpW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/seasonal_agriculture_performance_dataset (2).csv')

df.head()

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.info()

df.columns

df.describe()

df.isnull().sum()

df.isnull().sum().sum()

df.duplicated().sum()

df = df.drop_duplicates()

df.dtypes

df['Season'].unique()

df['Season'].value_counts()

plt.figure(figsize=(8,5))

sns.countplot(data=df, x='Season')

plt.title('Number of Agricultural Records by Season')
plt.xlabel('Season')
plt.ylabel('Number of Records')

plt.show()

season_yield = df.groupby('Season')['Yield_Tonnes_Ha'].mean().sort_values(ascending=False)

print(season_yield)

plt.figure(figsize=(8,5))

season_yield.plot(kind='bar')

plt.title('Average Yield by Season')
plt.xlabel('Season')
plt.ylabel('Average Yield (Tonnes/Ha)')

plt.xticks(rotation=0)
plt.show()

season_production = df.groupby('Season')['Production_Tonnes'].mean()

print(season_production)

season_profit = df.groupby('Season')['Profit_INR'].mean().sort_values(ascending=False)

print(season_profit)

plt.figure(figsize=(8,5))

season_profit.plot(kind='bar')

plt.title('Average Profit by Season')
plt.xlabel('Season')
plt.ylabel('Average Profit (INR)')

plt.xticks(rotation=0)
plt.show()

season_revenue = df.groupby('Season')['Revenue_INR'].mean().sort_values(ascending=False)

print(season_revenue)

plt.figure(figsize=(8,5))

season_revenue.plot(kind='bar')

plt.title('Average Revenue by Season')
plt.xlabel('Season')
plt.ylabel('Average Revenue (INR)')

plt.xticks(rotation=0)
plt.show()

season_cost = df.groupby('Season')['Total_Cost_INR'].mean().sort_values(ascending=False)

print(season_cost)

plt.figure(figsize=(8,5))

season_cost.plot(kind='bar')

plt.title('Average Agricultural Cost by Season')
plt.xlabel('Season')
plt.ylabel('Average Cost (INR)')

plt.xticks(rotation=0)
plt.show()

rainfall_season = df.groupby('Season')['Rainfall_mm'].mean()

print(rainfall_season)

plt.figure(figsize=(8,5))

rainfall_season.plot(kind='bar')

plt.title('Average Rainfall by Season')
plt.xlabel('Season')
plt.ylabel('Rainfall (mm)')

plt.xticks(rotation=0)
plt.show()

temperature_season = df.groupby('Season')['Avg_Temperature_C'].mean()

print(temperature_season)

plt.figure(figsize=(8,5))

temperature_season.plot(kind='bar')

plt.title('Average Temperature by Season')
plt.xlabel('Season')
plt.ylabel('Temperature (°C)')

plt.xticks(rotation=0)
plt.show()

soil_moisture = df.groupby('Season')['Soil_Moisture_pct'].mean()

print(soil_moisture)

plt.figure(figsize=(8,5))

soil_moisture.plot(kind='bar')

plt.title('Average Soil Moisture by Season')
plt.xlabel('Season')
plt.ylabel('Soil Moisture (%)')

plt.xticks(rotation=0)
plt.show()

pd.crosstab(df['Season'], df['Irrigation_Method'])

irrigation_season = pd.crosstab(
    df['Season'],
    df['Irrigation_Method']
)

irrigation_season.plot(
    kind='bar',
    figsize=(10,6)
)

plt.title('Irrigation Methods Across Seasons')
plt.xlabel('Season')
plt.ylabel('Number of Records')

plt.xticks(rotation=0)
plt.show()

water_season = df.groupby('Season')['Water_Used_m3'].mean()

print(water_season)

plt.figure(figsize=(8,5))

water_season.plot(kind='bar')

plt.title('Average Water Usage by Season')
plt.xlabel('Season')
plt.ylabel('Water Used (m³)')

plt.xticks(rotation=0)
plt.show()

water_efficiency = df.groupby('Season')['Water_Efficiency_t_per_1000m3'].mean()

print(water_efficiency)

plt.figure(figsize=(8,5))

water_efficiency.plot(kind='bar')

plt.title('Water Efficiency by Season')
plt.xlabel('Season')
plt.ylabel('Water Efficiency (Tonnes/1000m³)')

plt.xticks(rotation=0)
plt.show()

risk_season = df.groupby('Season')['Disease_Pest_Risk_pct'].mean()

print(risk_season)

plt.figure(figsize=(8,5))

risk_season.plot(kind='bar')

plt.title('Average Disease and Pest Risk by Season')
plt.xlabel('Season')
plt.ylabel('Risk (%)')

plt.xticks(rotation=0)
plt.show()

df['Crop'].value_counts()

crop_season_yield = df.groupby(
    ['Season', 'Crop']
)['Yield_Tonnes_Ha'].mean()

print(crop_season_yield)

plt.figure(figsize=(12,6))

sns.barplot(
    data=df,
    x='Season',
    y='Yield_Tonnes_Ha',
    hue='Crop',
    errorbar=None
)

plt.title('Crop Yield Across Seasons')
plt.xlabel('Season')
plt.ylabel('Yield (Tonnes/Ha)')

plt.show()

state_profit = df.groupby('State')['Profit_INR'].mean().sort_values(ascending=False)

print(state_profit)

plt.figure(figsize=(12,6))

state_profit.plot(kind='bar')

plt.title('Average Profit by State')
plt.xlabel('State')
plt.ylabel('Average Profit (INR)')

plt.xticks(rotation=45)
plt.show()

numeric_df = df.select_dtypes(include=np.number)

correlation = numeric_df.corr()

plt.figure(figsize=(16,12))

sns.heatmap(
    correlation,
    cmap='coolwarm',
    center=0
)

plt.title('Correlation Matrix of Agricultural Variables')

plt.show()

yield_corr = numeric_df.corr()['Yield_Tonnes_Ha'].sort_values(ascending=False)

print(yield_corr)

profit_corr = numeric_df.corr()['Profit_INR'].sort_values(ascending=False)

print(profit_corr)

df.groupby('Season')['Yield_Tonnes_Ha'].describe()

df.groupby('Season')['Profit_INR'].describe()

season_summary = df.groupby('Season').agg({
    'Yield_Tonnes_Ha': 'mean',
    'Production_Tonnes': 'mean',
    'Revenue_INR': 'mean',
    'Total_Cost_INR': 'mean',
    'Profit_INR': 'mean',
    'Rainfall_mm': 'mean',
    'Avg_Temperature_C': 'mean',
    'Water_Used_m3': 'mean',
    'Water_Efficiency_t_per_1000m3': 'mean',
    'Disease_Pest_Risk_pct': 'mean'
}).round(2)

season_summary

best_yield_season = season_summary['Yield_Tonnes_Ha'].idxmax()
best_profit_season = season_summary['Profit_INR'].idxmax()
best_water_season = season_summary['Water_Efficiency_t_per_1000m3'].idxmax()

print("Best season for yield:", best_yield_season)
print("Best season for profit:", best_profit_season)
print("Best season for water efficiency:", best_water_season)